In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("../../data/processed/master.csv")

print(df.shape)
df.head()

(4668, 103)

,Name_bal,BSE Code_bal,NSE Code_bal,Industry_bal,Current Price_bal,Debt,Equity capital,Preference capital,Reserves,Secured loan,...,Change in DII holding,DII holding,Book value preceding year,Return on capital employed preceding year,Return on assets preceding year,Return on equity preceding year,Number of Shareholders preceding quarter,t_1_price,future_return,signal
0,20 Microns,533022.0,20MICRONS,Mining / Minerals / Metals,225.45,121.37,17.64,0.0,335.31,82.32,...,0.00,0.00,83.20,19.27,8.10,15.34,20546.0,229.42,0.017609,Hold
1,21st Cent. Mgmt.,526921.0,21STCENMGM,Finance & Investments,70.44,4.17,10.50,0.0,42.88,0.00,...,0.00,0.00,18.87,-43.10,-38.53,-62.72,6333.0,72.33,0.026831,Hold
2,360 ONE,542772.0,360ONE,Finance & Investments,999.10,9471.93,35.89,0.0,3413.84,7636.08,...,-0.53,8.34,87.67,13.33,6.00,21.41,42622.0,1025.83,0.026754,Hold
3,3B Blackbio,532067.0,__NA__,Healthcare,1194.20,0.85,8.57,0.0,214.48,1.12,...,0.71,1.89,228.05,19.06,12.77,16.00,10088.0,1329.94,0.113666,Buy
4,3C IT Solutions,544190.0,__NA__,Computers - Software - Medium / Small,44.10,13.40,0.36,0.0,3.74,9.54,...,NaN,0.00,NaN,29.33,4.19,53.37,NaN,45.14,0.023583,Hold

In [2]:
numeric_cols = df.select_dtypes(include=np.number).columns

print(len(numeric_cols))

95

In [3]:
df.select_dtypes(exclude=np.number).columns.tolist()

['Name_bal',
 'NSE Code_bal',
 'Industry_bal',
 'join_key',
 'Name_rat',
 'NSE Code_rat',
 'Industry_rat',
 'signal']

In [4]:
target_rows = 50000

sampled_df = df.sample(
    n=target_rows,
    replace=True,
    random_state=42
).reset_index(drop=True)

print(sampled_df.shape)

(50000, 103)

In [5]:
np.random.seed(42)

for col in numeric_cols:

    std = sampled_df[col].std()

    noise = np.random.normal(
        loc=0,
        scale=std * 0.02,
        size=len(sampled_df)
    )

    sampled_df[col] = sampled_df[col] + noise

In [6]:
print(sampled_df.shape)

sampled_df.head()

(50000, 103)

,Name_bal,BSE Code_bal,NSE Code_bal,Industry_bal,Current Price_bal,Debt,Equity capital,Preference capital,Reserves,Secured loan,...,Change in DII holding,DII holding,Book value preceding year,Return on capital employed preceding year,Return on assets preceding year,Return on equity preceding year,Number of Shareholders preceding quarter,t_1_price,future_return,signal
0,Cords Cable,534487.570450,CORDSCABLE,Cables - Power,239.637534,2087.137913,45.300672,1.223275,328.134416,-274.713645,...,-0.004575,-0.157991,-12.327537,7.443265,0.565488,3.330234,14652.917399,220.540231,0.017381,Hold
1,Sinnar Bidi Udy.,509456.499920,__NA__,Miscellaneous,716.119860,-2252.536496,-2.358341,-0.073802,547.708963,139.897959,...,0.001672,0.354759,179.459455,-14.540035,-1.231994,-4.466311,4710.601261,695.875443,-0.012581,Hold
2,Prevest Denpro,545379.644680,__NA__,Healthcare,549.737652,1121.900657,-13.593704,-1.041328,-63.289448,-30.839175,...,-0.040611,0.722796,178.884055,38.014814,18.746173,23.868547,3762.502946,530.703548,0.082611,Buy
3,Bajaj Auto,537719.109635,BAJAJ-AUTO,Automobiles - Scooters And 3 - Wheelers,9710.242339,704.442236,312.072496,-1.087618,29092.421643,879.512696,...,-0.215036,8.602443,1366.939480,32.649825,18.836152,23.505459,210482.864988,10710.533166,0.108428,Buy
4,VCU Data Managem,535942.939457,__NA__,Trading,46.088524,-638.320619,12.825594,-0.268373,-601.278982,196.014796,...,0.048275,-0.072058,-83.744125,7.459471,3.396912,-0.409691,19236.199342,64.382493,-0.134625,Sell

In [7]:
sampled_df.to_csv(
    "../data/big_stock_dataset_50k.csv",
    index=False
)

print("Dataset saved successfully")

Dataset saved successfully

In [9]:
sampled_df.shape
sampled_df.memory_usage(deep=True).sum() / 1024**2

np.float64(43.960065841674805)

In [10]:
target_rows = 500000

big_df = df.sample(
    n=target_rows,
    replace=True,
    random_state=42
).reset_index(drop=True)

print(big_df.shape)

(500000, 103)

In [11]:
np.random.seed(42)

for col in numeric_cols:

    std = big_df[col].std()

    noise = np.random.normal(
        loc=0,
        scale=std * 0.02,
        size=len(big_df)
    )

    big_df[col] = big_df[col] + noise

In [12]:
print(big_df.shape)

memory_mb = (
    big_df.memory_usage(deep=True).sum()
    / 1024**2
)

print(f"Memory Usage: {memory_mb:.2f} MB")

(500000, 103)
Memory Usage: 439.54 MB

In [13]:
big_df.to_csv(
    "../data/big_stock_dataset_500k.csv",
    index=False
)

print("500K dataset saved")

500K dataset saved